# This is a sample build configuration for PHP.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
# - git ftp init -u $FTP_USERNAME --passwd $FTP_PASSWORD ftp://designwe.ftp.ukraine.com.ua$FTP_PATH
image: phpunit/phpunit:5.0.3

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp init -u $FTP_USERNAME --passwd $FTP_PASSWORD ftp://designwe.ftp.ukraine.com.ua$FTP_PATH
#            - git ftp push -u $FTP_USERNAME --passwd $FTP_PASSWORD ftp://designwe.ftp.ukraine.com.ua$FTP_PATH